# eco_* Felder sind illustrative Annahmen für die Demo-Modelle (keine anbieterbestätigten
# Werte), sie treiben nur den manuellen EcoLogits-Berechnungspfad (kein ecologits_provider
# gesetzt -> nie der anbieter-basierte Lookup, siehe ecologits_service.py).
MODELS = [
 {"provider":"Ollama","model_id":"local-small","display_name":"Lokales kleines Modell","hosting_region":"Lokal","is_eu_hosted":True,"model_class":"local_small","input_cost":0,"output_cost":0,"context_window":8192,"latency_ms":250,"input_energy":0.0008,"output_energy":0.002,"ecologits_provider":None,"eco_active_params_b":3,"eco_total_params_b":3,"eco_datacenter_pue":None,"eco_datacenter_wue":None,"eco_electricity_mix_zone":None},
 {"provider":"Ollama","model_id":"local-large","display_name":"Lokales großes Modell","hosting_region":"Lokal","is_eu_hosted":True,"model_class":"local_large","input_cost":0,"output_cost":0,"context_window":32768,"latency_ms":700,"input_energy":0.002,"output_energy":0.006,"ecologits_provider":None,"eco_active_params_b":13,"eco_total_params_b":13,"eco_datacenter_pue":None,"eco_datacenter_wue":None,"eco_electricity_mix_zone":None},
 {"provider":"Demo Cloud","model_id":"cloud-small","display_name":"Cloud Small (Demo)","hosting_region":"Global","is_eu_hosted":False,"model_class":"cloud_small","input_cost":0.5,"output_cost":1.5,"context_window":128000,"latency_ms":500,"input_energy":0.0005,"output_energy":0.0015,"ecologits_provider":None,"eco_active_params_b":8,"eco_total_params_b":8,"eco_datacenter_pue":None,"eco_datacenter_wue":None,"eco_electricity_mix_zone":None},
 {"provider":"Demo Cloud","model_id":"cloud-large","display_name":"Cloud Large (Demo)","hosting_region":"Global","is_eu_hosted":False,"model_class":"cloud_large","input_cost":5,"output_cost":15,"context_window":128000,"latency_ms":900,"input_energy":0.0015,"output_energy":0.005,"ecologits_provider":None,"eco_active_params_b":70,"eco_total_params_b":70,"eco_datacenter_pue":None,"eco_datacenter_wue":None,"eco_electricity_mix_zone":None},
 {"provider":"EU Demo","model_id":"eu-hosted","display_name":"EU Hosted (Demo)","hosting_region":"EU","is_eu_hosted":True,"model_class":"eu_hosted","input_cost":2,"output_cost":6,"context_window":64000,"latency_ms":650,"input_energy":0.0007,"output_energy":0.0022,"ecologits_provider":None,"eco_active_params_b":20,"eco_total_params_b":20,"eco_datacenter_pue":None,"eco_datacenter_wue":None,"eco_electricity_mix_zone":None},
]

